[package]
name = "client"
version = "0.1.0"
edition = "2024"

[dependencies]

rps_lib = { path = "../rps_lib" }

tokio = { version = "1.21", features = ["full"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
port_check = "0.2.1"
